### ISSUE TITLE
Larger tasks / fixes

### ISSUE THREAD

**Issue by serejandmyself** [citizenweb3/validatorinfo#138]
## Front/+
- [x] Charts | #16 | #209 
- [x] Validator profile visual | #39 |
- [x] Rumors | #120 |
- [ ] Opt out / Opt in | #128 |
- [x] Main page load | #61 |

## Back
- [x] Staking calculator | #62 |
- [x] Minimal backend | #113 |
- [x] Search function | #60 |
