### ISSUE TITLE
Design of pages (site map)

### ISSUE THREAD

**Issue by serejandmyself** [citizenweb3/validatorinfo#33]
- [x] Main page: validatorinfo.com | #131 |
- [x] Val Profile page: validatorinfo.com/validators/X
- [x] Val network page: validatorinfo.com/validators/X/cosmoshub | #26 | 
- [x] 404 page: in progress or error (same visual for `...` tabs)
- [x] Network profile page: validatorinfo.com/networks/X
- [x] Complex metrics page: validatorinfo.com/metrics/X | #38 | 
- [x] Library page: validatorinfo.com/library | #37 
- [x] Assist page: 5 direct shortcuts to val, chains, metrics, ai, etc 
- [x] About us page: validatorinfo.com/about | #119 
- [x] Logged in Dashboard page: validatorinfo.com/myarea | #8, #11 |  
- [x] TX page: validatorinfo.com/validators/X/cosmoshub/tx1 OR validaotrinfo.com/networks/cosmoshub/tx | #19 | 
- [x] Proposal detail page: validatorinfo.com/validators/X/cosmoshub/prop1 OR validaotrinfo.com/networks/cosmoshub/proposals  | #20 | 
- [x] Mobile version: self-explanatory| #129  
- [x] Account page: validatorinfo.com/networks/cosmoshub/accounts
- [x] Nodes page
- [x] Ecosystem page
